name: "P6 GHA: Github Action Linter"
description: "P6 GHA: Github Action Linter"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub Token"
    required: true
  actionlint:
    description: "Runs actionlint on workflows"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1

    - name: Ensure gh is installed (for act)
      if: ${{ inputs.actionlint == 'true' }}
      shell: bash
      run: |
        if [ "${ACT}" = "true" ]; then
          echo "Detected act runner. Installing gh via apt..."
          apt-get update -qq
          apt-get install -y -qq gh
        else
          echo "Running on GitHub-hosted runner, gh is already available."
        fi

    - name: "Lint GitHub Actions Workflows"
      if: ${{ inputs.actionlint == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        gh extension install cschleiden/gh-actionlint
        gh actionlint -verbose -shellcheck=shellcheck -pyflakes=pyflakes -color
