name: "P6 GHA: Github Action Linter"
description: "P6 GHA: Github Action Linter"
author: "Philip M. Gollucci"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: "Lint GitHub Actions Workflows"
      shell: bash
      run: gh actionlint -verbose -shellcheck=shellcheck -pyflakes=pyflakes -color
