name: "P6 GHA: Github Action Linter"
description: "P6 GHA: Github Action Linter"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Ensure gh is installed (for act)
      shell: bash
      run: |
        if [ "${ACT}" = "true" ]; then
          echo "Detected act runner. Installing gh via apt..."
          apt-get update -qq
          apt-get install -y -qq gh
        else
          echo "Running on GitHub-hosted runner, gh is already available."
        fi

    - name: "Lint GitHub Actions Workflows"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        gh extension install cschleiden/gh-actionlint
        gh actionlint -verbose -shellcheck=shellcheck -pyflakes=pyflakes -color
